# Generated by Django 5.0.14 on 2025-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_employment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employment_end_date',
            field=models.DateField(blank=True, help_text='Si se establece, el colaborador deja de estar disponible para turnos a partir del día siguiente.', null=True, verbose_name='Fecha de retiro'),
        ),
    ]
