# Generated by Django 5.0.14 on 2025-11-07 00:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0011_weightsamplesession_production_room_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasingExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('scope', models.CharField(choices=[('farm', 'Granjas'), ('plant', 'Planta'), ('office', 'Oficinas'), ('logistics', 'Logística')], default='farm', max_length=20, verbose_name='Ámbito')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('iva_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='IVA (%)')),
                ('withholding_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retención (%)')),
                ('requires_invoice', models.BooleanField(default=True, verbose_name='Exige factura')),
                ('requires_supporting_docs', models.BooleanField(default=False, verbose_name='Documentos obligatorios')),
                ('mandatory_documents', models.CharField(blank=True, max_length=255, verbose_name='Documentos solicitados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de gasto',
                'verbose_name_plural': 'Tipos de gasto',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre comercial')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('tax_regime', models.CharField(choices=[('general', 'Régimen general'), ('simplificado', 'Régimen simplificado'), ('especial', 'Régimen especial')], default='general', max_length=20, verbose_name='Régimen')),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='Plazo de pago (días)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ciudad')),
                ('bank_name', models.CharField(blank=True, max_length=150, verbose_name='Banco')),
                ('bank_account_type', models.CharField(choices=[('checking', 'Cuenta corriente'), ('savings', 'Cuenta de ahorros'), ('other', 'Otro')], default='checking', max_length=20, verbose_name='Tipo de cuenta')),
                ('bank_account_number', models.CharField(blank=True, max_length=64, verbose_name='Número de cuenta')),
                ('requires_vat_retention', models.BooleanField(default=False, verbose_name='Retención IVA')),
                ('requires_ica_retention', models.BooleanField(default=False, verbose_name='Retención ICA')),
                ('requires_rtefte', models.BooleanField(default=False, verbose_name='Retefuente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CostCenterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('scope', models.CharField(choices=[('farm', 'Granjas'), ('plant', 'Planta'), ('office', 'Oficinas'), ('logistics', 'Logística')], max_length=20, verbose_name='Ámbito')),
                ('allocation_method', models.CharField(choices=[('manual', 'Manual'), ('area', 'Por área'), ('production', 'Producción'), ('headcount', 'Headcount')], default='manual', max_length=20, verbose_name='Método de asignación')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('valid_from', models.DateField(verbose_name='Válido desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('chicken_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='production.chickenhouse', verbose_name='Galpón')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='production.farm', verbose_name='Granja')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='administration.purchasingexpensetype', verbose_name='Tipo de gasto')),
            ],
            options={
                'verbose_name': 'Configuración de centro de costo',
                'verbose_name_plural': 'Configuraciones de centros de costo',
                'ordering': ('-valid_from', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeline_code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('aprobacion', 'En aprobación'), ('ordenado', 'Orden emitida'), ('recepcion', 'Recepción'), ('factura', 'Factura'), ('pago', 'Pago'), ('archivada', 'Archivada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('currency', models.CharField(default='COP', max_length=3, verbose_name='Moneda')),
                ('estimated_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total estimado')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('order_number', models.CharField(blank=True, max_length=60, verbose_name='Número de orden')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Fecha de orden')),
                ('reception_notes', models.TextField(blank=True, verbose_name='Notas de recepción')),
                ('invoice_number', models.CharField(blank=True, max_length=60, verbose_name='Número de factura')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha factura')),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total factura')),
                ('payment_account', models.CharField(blank=True, max_length=120, verbose_name='Cuenta de pago')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('payment_notes', models.TextField(blank=True, verbose_name='Notas de pago')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='administration.costcenterconfig', verbose_name='Centro de costo')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='administration.purchasingexpensetype', verbose_name='Tipo de gasto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='administration.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Solicitud de compra',
                'verbose_name_plural': 'Solicitudes de compra',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('unit', models.CharField(max_length=30, verbose_name='Unidad')),
                ('batch_code', models.CharField(blank=True, max_length=60, verbose_name='Lote')),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto estimado')),
                ('chicken_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='production.chickenhouse', verbose_name='Galpón')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='production.farm', verbose_name='Granja')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='administration.purchaserequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Item de compra',
                'verbose_name_plural': 'Items de compra',
            },
        ),
        migrations.CreateModel(
            name='ExpenseTypeApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Secuencia')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del paso')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_type_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Aprobador')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='administration.purchasingexpensetype', verbose_name='Tipo de gasto')),
            ],
            options={
                'verbose_name': 'Regla de aprobación',
                'verbose_name_plural': 'Reglas de aprobación',
                'ordering': ('expense_type', 'sequence'),
                'unique_together': {('expense_type', 'sequence')},
            },
        ),
    ]
