# Generated by Django 5.0.14 on 2025-11-07 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Secuencia')),
                ('role', models.CharField(max_length=150, verbose_name='Rol')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='Estado')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Decidido en')),
            ],
            options={
                'verbose_name': 'Aprobación de compra',
                'verbose_name_plural': 'Aprobaciones de compra',
                'ordering': ('purchase_request', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=120, verbose_name='Evento')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Log de auditoría',
                'verbose_name_plural': 'Logs de auditoría',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='expensetypeapprovalrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprobado en'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobacion', 'En aprobación'), ('aprobada', 'Aprobada'), ('ordenado', 'Orden emitida'), ('recepcion', 'Recepción'), ('factura', 'Factura'), ('pago', 'Pago'), ('archivada', 'Archivada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddConstraint(
            model_name='expensetypeapprovalrule',
            constraint=models.UniqueConstraint(fields=('expense_type', 'sequence'), name='unique_expense_type_sequence'),
        ),
        migrations.AddField(
            model_name='purchaseapproval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Aprobador'),
        ),
        migrations.AddField(
            model_name='purchaseapproval',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='administration.purchaserequest', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='purchaseapproval',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_approvals', to='administration.expensetypeapprovalrule', verbose_name='Regla'),
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AddField(
            model_name='purchaseauditlog',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='administration.purchaserequest', verbose_name='Solicitud'),
        ),
        migrations.AddConstraint(
            model_name='purchaseapproval',
            constraint=models.UniqueConstraint(fields=('purchase_request', 'sequence'), name='unique_purchase_request_sequence'),
        ),
    ]
