# Generated by Django 5.0.14 on 2025-11-07 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_purchaseapproval_purchaseauditlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasingexpensetype',
            options={'ordering': ('name',), 'verbose_name': 'Categoría de gasto', 'verbose_name_plural': 'Categorías de gasto'},
        ),
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='mandatory_documents',
        ),
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='requires_supporting_docs',
        ),
        migrations.AddField(
            model_name='purchasingexpensetype',
            name='requires_self_withholding',
            field=models.BooleanField(default=False, verbose_name='Autoretención'),
        ),
        migrations.AlterField(
            model_name='costcenterconfig',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='administration.purchasingexpensetype', verbose_name='Categoría de gasto'),
        ),
        migrations.AlterField(
            model_name='expensetypeapprovalrule',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='administration.purchasingexpensetype', verbose_name='Categoría de gasto'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='administration.purchasingexpensetype', verbose_name='Categoría de gasto'),
        ),
    ]
