# Generated by Django 5.0.14 on 2025-11-07 01:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def copy_autoretencion_and_scope(apps, schema_editor):
    ExpenseType = apps.get_model('administration', 'PurchasingExpenseType')
    CostCenter = apps.get_model('administration', 'CostCenterConfig')

    scope_map = {
        'plant': 'lot',
        'office': 'house',
    }

    for expense_type in ExpenseType.objects.all():
        requires_self_withholding = getattr(expense_type, 'requires_self_withholding', False)
        expense_type.self_withholding_rate = Decimal('1.00') if requires_self_withholding else Decimal('0.00')
        if expense_type.scope in scope_map:
            expense_type.scope = scope_map[expense_type.scope]
        expense_type.save(update_fields=['self_withholding_rate', 'scope'])

    for cost_center in CostCenter.objects.all():
        if cost_center.scope in scope_map:
            cost_center.scope = scope_map[cost_center.scope]
            cost_center.save(update_fields=['scope'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_purchasingexpensetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasingexpensetype',
            name='self_withholding_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Autoretención (%)'),
        ),
        migrations.RunPython(copy_autoretencion_and_scope, noop),
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='requires_self_withholding',
        ),
        migrations.AlterField(
            model_name='costcenterconfig',
            name='scope',
            field=models.CharField(choices=[('farm', 'Granja'), ('lot', 'Lote'), ('house', 'Galpón'), ('logistics', 'Logística')], max_length=20, verbose_name='Ámbito'),
        ),
        migrations.AlterField(
            model_name='purchasingexpensetype',
            name='scope',
            field=models.CharField(choices=[('farm', 'Granja'), ('lot', 'Lote'), ('house', 'Galpón'), ('logistics', 'Logística')], default='farm', max_length=20, verbose_name='Ámbito'),
        ),
    ]
