# Generated by Django 5.0.14 on 2025-11-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_purchasingexpensetype_requires_self_withholding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='requires_invoice',
        ),
    ]
