# Generated by Django 5.0.14 on 2025-11-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_purchasingexpensetype_requires_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='cost_center',
        ),
        migrations.DeleteModel(
            name='CostCenterConfig',
        ),
    ]
