# Generated by Django 5.0.14 on 2025-11-07 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_remove_purchaserequest_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasingexpensetype',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='administration.purchasingexpensetype', verbose_name='Categoría padre'),
        ),
    ]
