# Generated by Django 5.0.14 on 2025-11-07 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_purchasingexpensetype_parent_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',), 'verbose_name': 'Tercero', 'verbose_name_plural': 'Terceros'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='bank_account_type',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms_days',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='requires_ica_retention',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='requires_rtefte',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='requires_vat_retention',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_regime',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='administration.supplier', verbose_name='Tercero'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre / Razón social'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='CC/NIT'),
        ),
    ]
