# Generated by Django 5.0.14 on 2025-11-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_supplier_options_and_more'),
        ('production', '0011_weightsamplesession_production_room_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='batch_code',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='chicken_house',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='scope_batch_code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Lote asociado'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='scope_chicken_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='production.chickenhouse', verbose_name='Galpón asociado'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='scope_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='production.farm', verbose_name='Granja asociada'),
        ),
        migrations.AddField(
            model_name='purchasingexpensetype',
            name='default_unit',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unidad base'),
        ),
    ]
