# Generated by Django 5.0.14 on 2025-11-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_remove_purchaseitem_batch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='support_document_type',
            field=models.CharField(choices=[('electronic_invoice', 'Factura Electrónica'), ('collection_account', 'Cuenta de Cobro'), ('equivalent_document', 'Documento Equivalente')], default='electronic_invoice', max_length=30, verbose_name='Tipo de soporte'),
        ),
        migrations.AddField(
            model_name='purchasingexpensetype',
            name='default_support_document_type',
            field=models.CharField(choices=[('electronic_invoice', 'Factura Electrónica'), ('collection_account', 'Cuenta de Cobro'), ('equivalent_document', 'Documento Equivalente')], default='electronic_invoice', max_length=30, verbose_name='Tipo de soporte por defecto'),
        ),
        migrations.AddField(
            model_name='purchasingexpensetype',
            name='support_concept_template',
            field=models.TextField(blank=True, help_text='Texto sugerido que se usará al generar documentos de soporte.', verbose_name='Plantilla concepto del soporte'),
        ),
    ]
