# Generated by Django 5.0.14 on 2025-11-07 13:34

from django.db import migrations, models


def _forward(apps, schema_editor):
    ExpenseType = apps.get_model('administration', 'PurchasingExpenseType')
    ExpenseType.objects.filter(scope='logistics').update(scope='company')


def _backward(apps, schema_editor):
    ExpenseType = apps.get_model('administration', 'PurchasingExpenseType')
    ExpenseType.objects.filter(scope='company').update(scope='logistics')


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_purchaserequest_support_document_type_and_more'),
    ]

    operations = [
        migrations.RunPython(_forward, _backward),
        migrations.AlterField(
            model_name='purchasingexpensetype',
            name='scope',
            field=models.CharField(choices=[('company', 'Empresa'), ('farm', 'Granja'), ('lot', 'Lote'), ('house', 'Galpón')], default='company', max_length=20, verbose_name='Ámbito'),
        ),
    ]
