# Generated by Django 5.0.14 on 2025-11-07 13:50

import django.db.models.deletion
from django.db import migrations, models


def _bootstrap_support_document_types(apps, schema_editor):
    SupportDocumentType = apps.get_model('administration', 'SupportDocumentType')
    PurchasingExpenseType = apps.get_model('administration', 'PurchasingExpenseType')
    PurchaseRequest = apps.get_model('administration', 'PurchaseRequest')

    defaults = {
        'electronic_invoice': ('Factura Electrónica', 'external'),
        'collection_account': ('Cuenta de Cobro', 'external'),
        'equivalent_document': ('Documento Equivalente', 'external'),
    }

    mapping: dict[str, int] = {}
    for code, (name, kind) in defaults.items():
        obj, _ = SupportDocumentType.objects.get_or_create(
            name=name,
            defaults={'kind': kind, 'template': ''},
        )
        mapping[code] = obj.pk

    for expense in PurchasingExpenseType.objects.all():
        code = getattr(expense, 'default_support_document_type', None)
        support_id = mapping.get(code)
        if support_id:
            expense.default_support_document_type_new_id = support_id
            expense.save(update_fields=['default_support_document_type_new'])

    for purchase in PurchaseRequest.objects.all():
        code = getattr(purchase, 'support_document_type', None)
        support_id = mapping.get(code)
        if support_id:
            purchase.support_document_type_new_id = support_id
            purchase.save(update_fields=['support_document_type_new'])


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_purchasingexpensetype_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('kind', models.CharField(choices=[('external', 'Soporte externo'), ('internal', 'Soporte interno')], default='external', max_length=20, verbose_name='Tipo')),
                ('template', models.TextField(blank=True, help_text='HTML usado para generar el soporte interno. Usa {{campo}} para valores dinámicos.', verbose_name='Plantilla soporte')),
            ],
            options={
                'verbose_name': 'Tipo de soporte',
                'verbose_name_plural': 'Tipos de soporte',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='purchasingexpensetype',
            name='default_support_document_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_categories', to='administration.supportdocumenttype', verbose_name='Tipo de soporte por defecto'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='support_document_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='administration.supportdocumenttype', verbose_name='Tipo de soporte'),
        ),
        migrations.RunPython(_bootstrap_support_document_types, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='default_support_document_type',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='support_document_type',
        ),
        migrations.RenameField(
            model_name='purchasingexpensetype',
            old_name='default_support_document_type_new',
            new_name='default_support_document_type',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='support_document_type_new',
            new_name='support_document_type',
        ),
    ]
