# Generated by Django 5.0.14 on 2025-11-07 18:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_purchaserequest_delivery_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad recibida'),
        ),
        migrations.CreateModel(
            name='PurchaseReceptionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='purchases/receptions/%Y/%m/', verbose_name='Archivo')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_attachments', to='administration.purchaserequest', verbose_name='Solicitud')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_reception_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de recepción',
                'verbose_name_plural': 'Adjuntos de recepción',
                'ordering': ('-created_at',),
            },
        ),
    ]
