# Generated by Django 5.0.14 on 2025-11-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_update_payment_source_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='default_unit',
        ),
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='self_withholding_rate',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='payment_condition',
            field=models.CharField(blank=True, choices=[('contado', 'Contado'), ('credito', 'Crédito'), ('credito_pagado', 'Crédito pagado')], max_length=20, verbose_name='Condiciones de pago'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='payment_source',
            field=models.CharField(choices=[('tbd', 'Por definir (TBD)'), ('treasury', 'Tesorería')], default='tbd', max_length=20, verbose_name='Origen del pago'),
        ),
    ]
