# Generated by Django 5.0.14 on 2025-11-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_remove_purchasingexpensetype_default_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetypeapprovalrule',
            options={'ordering': ('expense_type', 'id'), 'verbose_name': 'Regla de aprobación', 'verbose_name_plural': 'Reglas de aprobación'},
        ),
        migrations.RemoveConstraint(
            model_name='expensetypeapprovalrule',
            name='unique_expense_type_sequence',
        ),
        migrations.RemoveField(
            model_name='expensetypeapprovalrule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='expensetypeapprovalrule',
            name='sequence',
        ),
    ]
