# Generated by Django 5.0.14 on 2025-11-08 12:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_purchasingexpensetype_assumed_withholding_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingexpensetype',
            name='iva_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='IVA (%)'),
        ),
    ]
