# Generated by Django 5.0.14 on 2025-11-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_alter_purchasingexpensetype_iva_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasingexpensetype',
            name='is_active',
        ),
    ]
