# Generated by Django 5.0.14 on 2025-11-08 20:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_recalculate_purchase_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monto a pagar'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='reception_mismatch',
            field=models.BooleanField(default=False, verbose_name='Recepción con diferencias'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobacion', 'En aprobación'), ('aprobada', 'Aprobada'), ('ordenado', 'Orden emitida'), ('recepcion', 'Gestionar pago'), ('factura', 'Factura'), ('pago', 'Pago'), ('archivada', 'Archivada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
