# Generated by Django 5.0.14 on 2025-11-08 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0027_purchaserequest_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='support_template_values',
            field=models.JSONField(blank=True, default=dict, help_text='Valores usados para completar la plantilla interna.', verbose_name='Valores personalizados del soporte'),
        ),
        migrations.CreateModel(
            name='PurchaseSupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='purchases/support/%Y/%m/', verbose_name='Archivo')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_attachments', to='administration.purchaserequest', verbose_name='Solicitud')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_support_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de soporte',
                'verbose_name_plural': 'Adjuntos de soporte',
                'ordering': ('-created_at',),
            },
        ),
    ]
