# Generated by Django 5.0.14 on 2025-11-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0028_purchaserequest_support_template_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='accounted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de contabilización'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='accounted_in_system',
            field=models.BooleanField(
                default=False,
                help_text='Indica si la compra ya fue registrada en el sistema contable.',
                verbose_name='Contabilizado en sistema',
            ),
        ),
    ]
