# Generated by Django 5.0.14 on 2025-11-09 11:16

from django.db import migrations, models


def migrate_ordered_to_reception(apps, schema_editor):
    PurchaseRequest = apps.get_model('administration', 'PurchaseRequest')
    PurchaseRequest.objects.filter(status='ordenado').update(status='recepcion')


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0029_purchaserequest_accounted_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_ordered_to_reception, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobacion', 'En aprobación'), ('aprobada', 'Aprobada'), ('recepcion', 'Gestionar pago'), ('factura', 'Factura'), ('pago', 'Pago'), ('archivada', 'Archivada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
