# Generated by Django 5.0.14 on 2025-11-09 14:39

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def assign_manager_defaults(apps, schema_editor):
    PurchaseRequest = apps.get_model("administration", "PurchaseRequest")
    PurchaseRequest.objects.filter(
        assigned_manager__isnull=True,
        requester__isnull=False,
    ).update(assigned_manager=F("requester"))


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0030_alter_purchaserequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="assigned_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="managed_purchase_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gestor asignado",
            ),
        ),
        migrations.RunPython(assign_manager_defaults, migrations.RunPython.noop),
    ]
