# Generated by Django 5.0.14 on 2025-11-17 01:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_payrollsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Fecha de venta')),
                ('warehouse_destination', models.CharField(blank=True, choices=[('tierralta', 'Tierralta'), ('monteria', 'Montería'), ('bajo_cauca', 'Bajo Cauca')], max_length=32, verbose_name='Bodega (destino)')),
                ('status', models.CharField(choices=[('draft', 'Pre-factura'), ('confirmed', 'Venta confirmada'), ('paid', 'Venta pagada')], default='draft', max_length=20, verbose_name='Estado')),
                ('payment_condition', models.CharField(choices=[('cash', 'Contado'), ('credit', 'Crédito')], default='credit', max_length=20, verbose_name='Condición de pago')),
                ('payment_due_date', models.DateField(blank=True, null=True, verbose_name='Fecha esperada de pago')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total factura')),
                ('auto_withholding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Autorretención')),
                ('notes', models.TextField(blank=True, verbose_name='Notas para el equipo comercial')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado en')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado en')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_confirmed', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='administration.supplier', verbose_name='Cliente (tercero)')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.CharField(choices=[('jumbo', 'Jumbo'), ('aaa', 'AAA'), ('aa', 'AA'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('hen', 'Gallina'), ('hen_manure', 'Gallinaza')], max_length=16, verbose_name='Producto')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='administration.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
                'ordering': ('product_type',),
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Fecha de abono')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia')], default='cash', max_length=20, verbose_name='Modalidad')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas del abono')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='administration.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Abono de venta',
                'verbose_name_plural': 'Abonos de venta',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
