# Generated by Django 5.0.14 on 2025-11-19 11:28

import django.db.models.deletion
from django.db import migrations, models


AREA_SCOPE_COMPANY = "company"
AREA_SCOPE_FARM = "farm"
AREA_SCOPE_CHICKEN_HOUSE = "chicken_house"


def copy_scope_from_request(apps, schema_editor):
    PurchaseItem = apps.get_model('administration', 'PurchaseItem')
    PurchaseRequest = apps.get_model('administration', 'PurchaseRequest')
    try:
        area_scope = PurchaseRequest.AreaScope
        company_value = getattr(area_scope, 'COMPANY', AREA_SCOPE_COMPANY)
        farm_value = getattr(area_scope, 'FARM', AREA_SCOPE_FARM)
        chicken_house_value = getattr(area_scope, 'CHICKEN_HOUSE', AREA_SCOPE_CHICKEN_HOUSE)
    except AttributeError:
        company_value = AREA_SCOPE_COMPANY
        farm_value = AREA_SCOPE_FARM
        chicken_house_value = AREA_SCOPE_CHICKEN_HOUSE
    items = PurchaseItem.objects.select_related(
        'purchase__scope_farm',
        'purchase__scope_chicken_house__farm',
    )
    for item in items.iterator():
        purchase = item.purchase
        scope_area = getattr(purchase, 'scope_area', company_value) or company_value
        scope_farm_id = getattr(purchase, 'scope_farm_id', None)
        scope_house = getattr(purchase, 'scope_chicken_house', None)
        scope_house_id = getattr(purchase, 'scope_chicken_house_id', None)
        if scope_area == chicken_house_value and not scope_house_id:
            scope_area = farm_value if scope_farm_id else company_value
        if scope_area == chicken_house_value and not scope_farm_id and scope_house and scope_house.farm_id:
            scope_farm_id = scope_house.farm_id
        if scope_area == company_value:
            scope_farm_id = None
            scope_house_id = None
        elif scope_area == farm_value:
            scope_house_id = None
        item.scope_area = scope_area
        item.scope_farm_id = scope_farm_id
        item.scope_chicken_house_id = scope_house_id if scope_area == chicken_house_value else None
        item.save(update_fields=['scope_area', 'scope_farm', 'scope_chicken_house'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0033_sale_saleitem_salepayment'),
        ('production', '0020_eggdispatch_eggdispatchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='scope_area',
            field=models.CharField(choices=[('company', 'Empresa'), ('farm', 'Granja'), ('chicken_house', 'Galpón')], default='company', max_length=20, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='scope_chicken_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='production.chickenhouse', verbose_name='Galpón'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='scope_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='production.farm', verbose_name='Granja'),
        ),
        migrations.RunPython(copy_scope_from_request, noop),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='scope_area',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='scope_chicken_house',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='scope_farm',
        ),
    ]
