# Generated by Django 5.0.14 on 2025-11-25 00:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0034_remove_purchaserequest_scope_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Descuento aplicado",
            ),
        ),
    ]
