# Generated by Django 5.0.14 on 2025-11-26 00:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0035_sale_discount_and_withholding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de venta'),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de abono'),
        ),
    ]
