# Generated by Django 5.0.14 on 2025-11-26 01:20

from __future__ import annotations

from decimal import Decimal

from django.db import migrations
from django.db.models import Sum


def recompute_sale_financials(apps, schema_editor):
    Sale = apps.get_model("administration", "Sale")
    SaleItem = apps.get_model("administration", "SaleItem")
    SalePayment = apps.get_model("administration", "SalePayment")

    zero = Decimal("0")
    penny = Decimal("0.01")

    for sale in Sale.objects.all().iterator():
        subtotal = (
            SaleItem.objects.filter(sale_id=sale.pk).aggregate(total=Sum("subtotal")).get("total") or zero
        )
        subtotal_amount = Decimal(subtotal)
        discount = Decimal(sale.discount_amount or zero)
        net_total = subtotal_amount - discount
        if net_total < zero:
            net_total = zero
        net_total = net_total.quantize(penny)
        withholding = (net_total * penny).quantize(penny)

        payments_total = (
            SalePayment.objects.filter(sale_id=sale.pk).aggregate(total=Sum("amount")).get("total") or zero
        )
        payments_amount = Decimal(payments_total)
        balance = net_total - withholding - payments_amount
        if balance < zero:
            balance = zero

        updated_fields: set[str] = set()
        if sale.total_amount != net_total:
            sale.total_amount = net_total
            updated_fields.add("total_amount")
        if sale.auto_withholding_amount != withholding:
            sale.auto_withholding_amount = withholding
            updated_fields.add("auto_withholding_amount")

        new_status = sale.status
        new_paid_at = sale.paid_at
        if sale.status in ("confirmed", "paid"):
            if balance <= zero:
                new_status = "paid"
                if new_paid_at is None:
                    new_paid_at = sale.updated_at
            else:
                new_status = "confirmed"
                new_paid_at = None

        if new_status != sale.status:
            sale.status = new_status
            updated_fields.add("status")
        if new_paid_at != sale.paid_at:
            sale.paid_at = new_paid_at
            updated_fields.add("paid_at")

        if updated_fields:
            sale.save(update_fields=list(updated_fields))


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0036_alter_sale_date_alter_salepayment_date"),
    ]

    operations = [
        migrations.RunPython(recompute_sale_financials, migrations.RunPython.noop),
    ]
