# Generated by Django 5.0.14 on 2025-11-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0037_recalculate_sale_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='auto_withholding_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
    ]
