# Generated by Django 5.0.14 on 2025-12-02 14:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0040_refresh_sale_payment_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='retention_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retención aplicada'),
        ),
    ]
