# Generated by Django 5.0.14 on 2025-12-02 14:31

import django.core.validators
from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models
from django.db.models import Sum


def convert_retention_amount_to_percentage(apps, schema_editor):
    Sale = apps.get_model("administration", "Sale")
    SaleItem = apps.get_model("administration", "SaleItem")
    zero = Decimal("0.00")
    hundred = Decimal("100.00")
    penny = Decimal("0.01")

    sale_qs = Sale.objects.all().only("id", "discount_amount", "retention_amount")
    for sale in sale_qs.iterator(chunk_size=500):
        current_value = Decimal(sale.retention_amount or zero)
        if current_value <= zero:
            continue
        subtotal = (
            SaleItem.objects.filter(sale_id=sale.pk).aggregate(total=Sum("subtotal")).get("total") or zero
        )
        base_total = subtotal - Decimal(sale.discount_amount or zero)
        if base_total <= zero:
            sale.retention_amount = zero
            sale.save(update_fields=["retention_amount"])
            continue
        rate = (current_value / base_total) * hundred
        if rate > hundred:
            rate = hundred
        rate = rate.quantize(penny, rounding=ROUND_HALF_UP)
        sale.retention_amount = rate
        sale.save(update_fields=["retention_amount"])


def revert_retention_percentage_to_amount(apps, schema_editor):
    Sale = apps.get_model("administration", "Sale")
    SaleItem = apps.get_model("administration", "SaleItem")
    zero = Decimal("0.00")
    hundred = Decimal("100.00")
    penny = Decimal("0.01")

    sale_qs = Sale.objects.all().only("id", "discount_amount", "retention_amount")
    for sale in sale_qs.iterator(chunk_size=500):
        rate = Decimal(sale.retention_amount or zero)
        if rate <= zero:
            continue
        if rate > hundred:
            rate = hundred
        subtotal = (
            SaleItem.objects.filter(sale_id=sale.pk).aggregate(total=Sum("subtotal")).get("total") or zero
        )
        base_total = subtotal - Decimal(sale.discount_amount or zero)
        if base_total <= zero:
            sale.retention_amount = zero
            sale.save(update_fields=["retention_amount"])
            continue
        amount = (base_total * rate / hundred).quantize(penny, rounding=ROUND_HALF_UP)
        sale.retention_amount = amount
        sale.save(update_fields=["retention_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0041_sale_retention_amount'),
    ]

    operations = [
        migrations.RunPython(
            convert_retention_amount_to_percentage,
            reverse_code=revert_retention_percentage_to_amount,
        ),
        migrations.AlterField(
            model_name='sale',
            name='retention_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retención (%)'),
        ),
    ]
