# Generated by Django 5.0.14 on 2025-12-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0042_alter_sale_retention_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='support_group_code',
            field=models.CharField(blank=True, help_text='Identificador del lote de compras que comparten un único soporte.', max_length=32, verbose_name='Código de grupo de soporte'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='support_group_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_group_children', to='administration.purchaserequest', verbose_name='Líder del grupo de soporte'),
        ),
    ]
