# Generated by Django 5.0.14 on 2025-12-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0043_purchaserequest_support_group_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Alimento'), ('other', 'Otros')], default='other', help_text='Determina si se descontará automáticamente cuando los galponeros registren consumo.', max_length=20, verbose_name='Tipo'),
        ),
    ]
