# Generated by Django 5.0.14 on 2025-10-30 19:25

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('granjas', '0002_alter_birdbatch_options_and_more'),
        ('personal', '0019_backfill_assignment_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de tarea',
                'verbose_name_plural': 'Categorías de tareas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estado de tarea',
                'verbose_name_plural': 'Estados de tareas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tarea')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('task_type', models.CharField(choices=[('one_time', 'Única'), ('recurring', 'Recurrente')], default='one_time', max_length=16, verbose_name='Tipo')),
                ('scheduled_for', models.DateField(blank=True, help_text='Requerido solo cuando la tarea es de ejecución única.', null=True, verbose_name='Fecha programada')),
                ('weekly_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]), blank=True, default=list, help_text='Seleccione los días de la semana para tareas recurrentes semanales.', size=None, verbose_name='Días de la semana')),
                ('month_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]), blank=True, default=list, help_text='Seleccione los días del mes (1-31) para tareas recurrentes quincenales o mensuales.', size=None, verbose_name='Días del mes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_definitions', to='task_manager.taskcategory', verbose_name='Categoría')),
                ('chicken_houses', models.ManyToManyField(blank=True, related_name='task_definitions', to='granjas.chickenhouse', verbose_name='Galpones')),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_definitions', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador asignado')),
                ('farms', models.ManyToManyField(blank=True, related_name='task_definitions', to='granjas.farm', verbose_name='Granjas')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_definitions', to='personal.positiondefinition', verbose_name='Posición asignada')),
                ('rooms', models.ManyToManyField(blank=True, related_name='task_definitions', to='granjas.room', verbose_name='Salones')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_definitions', to='task_manager.taskstatus', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Definición de tarea',
                'verbose_name_plural': 'Definiciones de tareas',
                'ordering': ('name',),
            },
        ),
    ]
