# Generated by Django 5.0.14 on 2025-10-30 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionrecord_bird_batch'),
        ('task_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Fecha programada')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('production_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignment', to='production.productionrecord', verbose_name='Registro de producción')),
                ('task_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='task_manager.taskdefinition', verbose_name='Definición de tarea')),
            ],
            options={
                'verbose_name': 'Asignación de tarea',
                'verbose_name_plural': 'Asignaciones de tareas',
                'ordering': ('due_date', 'task_definition__name'),
                'unique_together': {('task_definition', 'collaborator', 'due_date')},
            },
        ),
    ]
