# Generated by Django 5.0.14 on 2025-10-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_taskassignment"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE task_manager_taskdefinition
                ADD COLUMN IF NOT EXISTS month_days smallint[] NOT NULL DEFAULT '{}';

                ALTER TABLE task_manager_taskdefinition
                ALTER COLUMN month_days DROP DEFAULT;
            """,
            reverse_sql="""
                ALTER TABLE task_manager_taskdefinition
                DROP COLUMN IF EXISTS month_days;
            """,
        ),
    ]

