# Generated by Django 5.0.14 on 2025-10-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_taskdefinition_month_days_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdefinition',
            name='evidence_requirement',
            field=models.CharField(choices=[('none', 'Sin evidencia'), ('photo', 'Fotografía obligatoria'), ('video', 'Video obligatorio'), ('photo_or_video', 'Foto o video obligatorio')], default='none', help_text='Define si la tarea exige evidencia multimedia (foto o video) al finalizar.', max_length=20, verbose_name='Requisito de evidencia'),
        ),
        migrations.AddField(
            model_name='taskdefinition',
            name='record_format',
            field=models.CharField(choices=[('none', 'No requiere formato'), ('production_record', 'Registro de producción')], default='none', help_text='Selecciona el formato de registro obligatorio para cerrar la tarea.', max_length=32, verbose_name='Formato de registro'),
        ),
    ]
