# Generated by Django 5.0.14 on 2025-10-31 01:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_taskdefinition_evidence_requirement_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='taskdefinition',
                    name='fortnight_days',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, help_text='Seleccione los días específicos dentro de la quincena (1-31) cuando aplique.', size=None, verbose_name='Días de quincena'),
                ),
                migrations.AddField(
                    model_name='taskdefinition',
                    name='monthly_week_days',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, help_text='Defina la semana del mes en la que se debe ejecutar (1 a 5) cuando aplique.', size=None, verbose_name='Semanas del mes'),
                ),
            ],
        ),
    ]
