# Generated by Django 5.0.14 on 2025-10-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_sync_schedule_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdefinition',
            name='task_type',
            field=models.CharField(blank=True, choices=[('one_time', 'Única'), ('recurring', 'Recurrente')], default=None, max_length=16, null=True, verbose_name='Tipo'),
        ),
    ]
