# Generated by Django 5.0.14 on 2025-10-31 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_taskdefinition_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdefinition',
            options={'ordering': ('display_order', 'name', 'pk'), 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='task_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='task_manager.taskdefinition', verbose_name='Tarea'),
        ),
    ]
