# Generated by Django 5.0.14 on 2025-11-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_load_task_manager_fixture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdefinition',
            options={'ordering': ('display_order', 'name', 'pk'), 'permissions': [('access_mini_app', 'Puede acceder a la mini app de tareas')], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
