# Generated by Django 5.0.14 on 2025-11-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_grant_mini_app_permission'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='taskdefinition',
                    name='criticality_level',
                    field=models.CharField(
                        choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')],
                        default='medium',
                        help_text='Define el nivel de impacto operativo si la tarea no se ejecuta.',
                        max_length=16,
                        verbose_name='Nivel de criticidad',
                    ),
                ),
                migrations.AddField(
                    model_name='taskdefinition',
                    name='is_mandatory',
                    field=models.BooleanField(
                        default=False,
                        help_text='Indica si la ejecución de la tarea es obligatoria.',
                        verbose_name='Obligatoria',
                    ),
                ),
            ],
        )
    ]
