# Generated by Django 5.0.14 on 2025-11-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_taskdefinition_criticality_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdefinition',
            options={'ordering': ('display_order', 'name', 'pk'), 'permissions': [('access_mini_app', 'Puede acceder a la mini app de tareas'), ('view_mini_app_motivation_card', 'Puede ver el card de motivación en la mini app'), ('view_mini_app_shift_confirmation_card', 'Puede ver el card de confirmación de turno en la mini app'), ('view_mini_app_production_card', 'Puede ver el card de producción en la mini app'), ('view_mini_app_production_summary_card', 'Puede ver el card de resumen de producción en la mini app'), ('view_mini_app_pending_classification_card', 'Puede ver el card de producciones pendientes en la mini app'), ('view_mini_app_transport_queue_card', 'Puede ver el card de cola de transporte en la mini app'), ('view_mini_app_egg_stage_cards', 'Puede ver los cards de etapas de huevo en la mini app'), ('view_mini_app_dispatch_form_card', 'Puede ver el card de formulario de despacho en la mini app'), ('view_mini_app_dispatch_detail_card', 'Puede ver el card de detalle de despacho en la mini app'), ('view_mini_app_daily_roster_card', 'Puede ver el card de asignaciones diarias en la mini app'), ('view_mini_app_task_cards', 'Puede ver los cards de tareas en la mini app')], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
