# Generated by hand to include the bird weight record format on 2025-11-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0019_alter_taskdefinition_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdefinition",
            name="record_format",
            field=models.CharField(
                choices=[
                    ("none", "No requiere formato"),
                    ("production_record", "Registro de producción"),
                    ("bird_weight", "Pesaje aves"),
                ],
                default="none",
                help_text="Selecciona el formato de registro obligatorio para cerrar la tarea.",
                max_length=32,
                verbose_name="Formato de registro",
            ),
        ),
    ]
