# Generated by Django 5.0.14 on 2025-11-09 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0024_alter_taskdefinition_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAppPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(choices=[('telegram', 'Telegram'), ('embedded', 'Embebido'), ('web', 'Web')], default='web', max_length=16, verbose_name='Cliente')),
                ('endpoint', models.URLField(max_length=1024, unique=True, verbose_name='Endpoint')),
                ('p256dh_key', models.CharField(max_length=255, verbose_name='Clave P256DH')),
                ('auth_key', models.CharField(max_length=128, verbose_name='Clave Auth')),
                ('content_encoding', models.CharField(default='aes128gcm', max_length=32, verbose_name='Codificación')),
                ('expiration_time', models.DateTimeField(blank=True, null=True, verbose_name='Expira')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_app_push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción push mini app',
                'verbose_name_plural': 'Suscripciones push mini app',
                'ordering': ('-updated_at',),
            },
        ),
    ]
