# Generated by Django 5.0.14 on 2025-11-09 21:47

from django.db import migrations


DROP_NOTIFICATIONS_TABLES_SQL = """
DROP TABLE IF EXISTS notifications_notificationdispatch CASCADE;
DROP TABLE IF EXISTS notifications_notificationevent CASCADE;
DROP TABLE IF EXISTS notifications_notificationpreference CASCADE;
DROP TABLE IF EXISTS notifications_notificationtemplate CASCADE;
DROP TABLE IF EXISTS notifications_telegraminboundupdate CASCADE;
DROP TABLE IF EXISTS notifications_telegramchatlink CASCADE;
DROP TABLE IF EXISTS notifications_notificationtopic CASCADE;
DROP TABLE IF EXISTS notifications_telegrambotconfig CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0026_alter_taskdefinition_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql=DROP_NOTIFICATIONS_TABLES_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
