# Generated by Django 5.0.14 on 2025-11-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0027_drop_notifications_tables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskdefinition",
            options={
                "ordering": ("display_order", "name", "pk"),
                "permissions": [
                    ("access_mini_app", "Puede acceder a la mini app de tareas"),
                    (
                        "view_mini_app_goals_selection_card",
                        "Puede ver el card de selección de plan de premio en la mini app",
                    ),
                    (
                        "view_mini_app_goals_overview_card",
                        "Puede ver el card de metas activas en la mini app",
                    ),
                    ("view_mini_app_shift_confirmation_card", "Puede ver el card de confirmación de turno en la mini app"),
                    ("view_mini_app_production_card", "Puede ver el card de producción en la mini app"),
                    ("view_mini_app_production_summary_card", "Puede ver el card de resumen de producción en la mini app"),
                    ("view_mini_app_weight_registry_card", "Puede ver el card de control de pesos en la mini app"),
                    ("view_mini_app_transport_queue_card", "Secuencia 1 · Lotes listos para transporte (mini app)"),
                    ("view_mini_app_egg_stage_cards", "Puede ver los cards de etapas de huevo en la mini app"),
                    (
                        "view_mini_app_egg_stage_transport_card",
                        "Secuencia 2 · Transporte interno (mini app)",
                    ),
                    (
                        "view_mini_app_egg_stage_verification_card",
                        "Secuencia 3 · Verificación en acopio (mini app)",
                    ),
                    (
                        "view_mini_app_pending_classification_card",
                        "Secuencia 4 · Producciones pendientes por clasificar (mini app)",
                    ),
                    (
                        "view_mini_app_egg_stage_classification_card",
                        "Secuencia 5 · Clasificación por tipos (mini app)",
                    ),
                    (
                        "view_mini_app_egg_stage_inspection_card",
                        "Secuencia 6 · Inspección final (mini app)",
                    ),
                    (
                        "view_mini_app_egg_stage_inventory_card",
                        "Secuencia 7 · Inventario listo para venta (mini app)",
                    ),
                    (
                        "view_mini_app_egg_stage_dispatches_card",
                        "Secuencia 8 · Despachos a ventas (mini app)",
                    ),
                    ("view_mini_app_dispatch_form_card", "Puede ver el card de formulario de despacho en la mini app"),
                    ("view_mini_app_dispatch_detail_card", "Puede ver el card de detalle de despacho en la mini app"),
                    ("view_mini_app_daily_roster_card", "Puede ver el card de asignaciones diarias en la mini app"),
                    ("view_mini_app_leader_review_card", "Puede ver el card de revisión de tareas en la mini app"),
                    ("view_mini_app_suggestions_card", "Puede ver el card de sugerencias enviadas en la mini app"),
                    ("view_mini_app_task_cards", "Puede ver los cards de tareas en la mini app"),
                    (
                        "view_mini_app_purchase_request_card",
                        "Puede ver el card de solicitud de compra en la mini app",
                    ),
                    (
                        "view_mini_app_purchase_overview_card",
                        "Puede ver el card de solicitudes de compra en la mini app",
                    ),
                    (
                        "view_mini_app_purchase_approval_card",
                        "Puede ver el card de aprobación de compras en la mini app",
                    ),
                    (
                        "view_mini_app_purchase_management_card",
                        "Puede ver el card de gestión de compras en la mini app",
                    ),
                ],
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
            },
        ),
    ]
