# Generated by Django 5.0.14 on 2025-11-13 16:30

from django.db import migrations


def update_permission_names(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    mapping = {
        "view_mini_app_transport_queue_card": "Secuencia 1 · Lotes listos para transporte (mini app)",
        "view_mini_app_pending_classification_card": "Secuencia 4 · Producciones pendientes por clasificar (mini app)",
    }
    permissions = Permission.objects.filter(codename__in=mapping.keys(), content_type__app_label="task_manager")
    for permission in permissions:
        new_name = mapping.get(permission.codename)
        if new_name and permission.name != new_name:
            permission.name = new_name
            permission.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0028_alter_taskdefinition_options"),
    ]

    operations = [
        migrations.RunPython(update_permission_names, migrations.RunPython.noop),
    ]
