# Generated by Django 5.0.14 on 2025-11-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0029_alter_taskdefinition_options'),
        ('task_manager', '0029_update_transport_permission_names'),
    ]

    operations = [
    ]
