# Generated by Django 5.0.14 on 2025-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0032_taskassignment_completion_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdefinition',
            name='record_format',
            field=models.CharField(choices=[('none', 'No requiere formato'), ('production_record', 'Registro de producción'), ('bird_weight', 'Pesaje aves'), ('whatsapp_night_report', 'Envio reporte nocturno Whatsapp'), ('supper_record', 'Registro Supercena'), ('farm_mortality_record', 'Registro Mortalidad Granja')], default='none', help_text='Selecciona el formato de registro obligatorio para cerrar la tarea.', max_length=32, verbose_name='Formato de registro'),
        ),
    ]
