# Generated by Django 5.0.14 on 2025-12-04 18:30

from django.db import migrations, models


DEPRECATED_RECORD_FORMATS = (
    "production_record",
    "whatsapp_night_report",
    "farm_mortality_record",
)


def reset_deprecated_record_formats(apps, schema_editor):
    TaskDefinition = apps.get_model("task_manager", "TaskDefinition")
    TaskDefinition.objects.filter(record_format__in=DEPRECATED_RECORD_FORMATS).update(
        record_format="none"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0033_alter_taskdefinition_record_format"),
    ]

    operations = [
        migrations.RunPython(reset_deprecated_record_formats, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="taskdefinition",
            name="record_format",
            field=models.CharField(
                choices=[
                    ("none", "No requiere formato"),
                    ("bird_weight", "Pesaje aves"),
                    ("supper_record", "Registro Supercena"),
                ],
                default="none",
                help_text="Selecciona el formato de registro obligatorio para cerrar la tarea.",
                max_length=32,
                verbose_name="Formato de registro",
            ),
        ),
    ]
