# Generated by Django 5.2.7 on 2025-10-26 09:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


SKILL_MAPPING = {
    'basic': 3,
    'intermediate': 6,
    'advanced': 9,
}


def populate_skill_scores(apps, schema_editor):
    Capability = apps.get_model('calendario', 'OperatorCapability')
    for capability in Capability.objects.all():
        max_complexity = getattr(capability, 'max_complexity', None)
        capability.skill_score = SKILL_MAPPING.get(max_complexity, 5)
        capability.save(update_fields=['skill_score'])


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_remove_positiondefinition_shift_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operatorcapability',
            unique_together={('operator', 'category')},
        ),
        migrations.AddField(
            model_name='operatorcapability',
            name='skill_score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nivel de habilidad'),
        ),
        migrations.RunPython(populate_skill_scores, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='operatorcapability',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='operatorcapability',
            name='effective_until',
        ),
        migrations.RemoveField(
            model_name='operatorcapability',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='operatorcapability',
            name='max_complexity',
        ),
        migrations.RemoveField(
            model_name='operatorcapability',
            name='min_complexity',
        ),
        migrations.RemoveField(
            model_name='operatorcapability',
            name='notes',
        ),
    ]
