# Generated by Django 5.2.7 on 2025-10-26 13:45

from django.db import migrations


def copy_preferred_farms(apps, schema_editor):
    Preference = apps.get_model('calendario', 'OperatorFarmPreference')
    UserProfile = apps.get_model('users', 'UserProfile')

    preferences = (
        Preference.objects.all()
        .order_by('-is_primary', 'preference_weight', 'id')
        .values('operator_id', 'farm_id')
    )

    chosen = {}
    for entry in preferences:
        operator_id = entry['operator_id']
        if operator_id in chosen:
            continue
        chosen[operator_id] = entry['farm_id']

    for operator_id, farm_id in chosen.items():
        UserProfile.objects.filter(pk=operator_id).update(preferred_farm_id=farm_id)


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_alter_operatorcapability_unique_together_and_more'),
        ('users', '0002_userprofile_preferred_farm'),
    ]

    operations = [
        migrations.RunPython(copy_preferred_farms, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='OperatorFarmPreference',
        ),
    ]
