# Generated by Django 5.2.7 on 2025-10-26 15:52

from django.db import migrations, models


def seed_position_display_order(apps, schema_editor):
    PositionDefinition = apps.get_model('calendario', 'PositionDefinition')
    ordered_positions = PositionDefinition.objects.all().order_by('farm__name', 'code', 'id')
    for index, position in enumerate(ordered_positions, start=1):
        PositionDefinition.objects.filter(pk=position.pk).update(display_order=index)


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_delete_operatorfarmpreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiondefinition',
            options={'ordering': ('display_order', 'id'), 'verbose_name': 'Definición de posición', 'verbose_name_plural': 'Definiciones de posiciones'},
        ),
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'ordering': ('date', 'position__display_order', 'position__code'), 'verbose_name': 'Asignación', 'verbose_name_plural': 'Asignaciones'},
        ),
        migrations.AddField(
            model_name='positiondefinition',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden de visualización'),
        ),
        migrations.RunPython(seed_position_display_order, migrations.RunPython.noop),
    ]
