# Generated by Django 5.0.14 on 2025-10-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0010_rename_calendario_o_operato_0eec88_idx_calendario__operato_4c829a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiondefinition',
            name='complexity',
            field=models.CharField(choices=[('support', 'Apoyo (opcional)'), ('basic', 'Baja prioridad'), ('intermediate', 'Prioridad media'), ('advanced', 'Alta prioridad'), ('critical', 'Crítico operativo')], default='basic', max_length=16, verbose_name='Nivel de criticidad'),
        ),
    ]
