# Generated by Django 5.0.14 on 2025-10-28 07:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0011_alter_positiondefinition_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioncategory',
            name='automatic_rest_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]), blank=True, default=list, help_text='Bloquea las asignaciones automáticas en los días seleccionados.', size=None, verbose_name='Días de descanso automático'),
        ),
    ]
