# Generated by Django 5.0.14 on 2025-10-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0014_remove_operatorcapability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positioncategory',
            options={'ordering': ('code',), 'verbose_name': 'Categoría de posición', 'verbose_name_plural': 'Categorías de posiciones'},
        ),
        migrations.RemoveField(
            model_name='positioncategory',
            name='extra_day_limit',
        ),
        migrations.RemoveField(
            model_name='positioncategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='positioncategory',
            name='overload_alert_level',
        ),
        migrations.RemoveField(
            model_name='positioncategory',
            name='overtime_points',
        ),
        migrations.RemoveField(
            model_name='positioncategory',
            name='rest_min_consecutive_days',
        ),
        migrations.RemoveField(
            model_name='positioncategory',
            name='rest_min_frequency',
        ),
    ]
