# Generated by Django 5.0.14 on 2025-10-29 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0017_remove_positiondefinition_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(fields=('calendar', 'operator', 'date'), name='uniq_calendar_operator_date'),
        ),
    ]
