# Generated by Django 5.2.7 on 2025-10-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChickenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chicken_houses', to='granjas.farm')),
            ],
            options={
                'verbose_name': 'Chicken House',
                'verbose_name_plural': 'Chicken Houses',
                'ordering': ('farm__name', 'name'),
                'unique_together': {('farm', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BirdBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=8)),
                ('birth_date', models.DateField()),
                ('initial_quantity', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=150)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bird_batches', to='granjas.farm')),
            ],
            options={
                'ordering': ('-birth_date', 'farm__name'),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chicken_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='granjas.chickenhouse')),
            ],
            options={
                'ordering': ('chicken_house__farm__name', 'chicken_house__name', 'name'),
                'unique_together': {('chicken_house', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BirdBatchRoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bird_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='granjas.birdbatch')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='granjas.room')),
            ],
            options={
                'verbose_name': 'Bird Batch Allocation',
                'verbose_name_plural': 'Bird Batch Allocations',
                'unique_together': {('bird_batch', 'room')},
            },
        ),
    ]
