# Generated by Django 5.2.7 on 2025-10-23 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birdbatch',
            options={'ordering': ('-birth_date', 'farm__name'), 'verbose_name': 'Lote de aves', 'verbose_name_plural': 'Lotes de aves'},
        ),
        migrations.AlterModelOptions(
            name='birdbatchroomallocation',
            options={'verbose_name': 'Asignacion de lote', 'verbose_name_plural': 'Asignaciones de lotes'},
        ),
        migrations.AlterModelOptions(
            name='chickenhouse',
            options={'ordering': ('farm__name', 'name'), 'verbose_name': 'Galpon', 'verbose_name_plural': 'Galpones'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ('name',), 'verbose_name': 'Granja', 'verbose_name_plural': 'Granjas'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('chicken_house__farm__name', 'chicken_house__name', 'name'), 'verbose_name': 'Salon', 'verbose_name_plural': 'Salones'},
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='breed',
            field=models.CharField(max_length=150, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bird_batches', to='granjas.farm', verbose_name='Granja'),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='initial_quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad inicial'),
        ),
        migrations.AlterField(
            model_name='birdbatch',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=8, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='birdbatchroomallocation',
            name='bird_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='granjas.birdbatch', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='birdbatchroomallocation',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='birdbatchroomallocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='granjas.room', verbose_name='Salon'),
        ),
        migrations.AlterField(
            model_name='chickenhouse',
            name='area_m2',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area (m2)'),
        ),
        migrations.AlterField(
            model_name='chickenhouse',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chicken_houses', to='granjas.farm', verbose_name='Granja'),
        ),
        migrations.AlterField(
            model_name='chickenhouse',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area_m2',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area (m2)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='chicken_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='granjas.chickenhouse', verbose_name='Galpon'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
