# Generated by Django 5.0.14 on 2025-10-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('production', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Produccion')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo')),
                ('mortality', models.PositiveIntegerField(verbose_name='Mortalidad')),
                ('discard', models.PositiveIntegerField(verbose_name='Descarte')),
            ],
            options={
                'verbose_name': 'Registro de produccion',
                'verbose_name_plural': 'Registros de produccion',
                'ordering': ('-date',),
            },
        ),
    ]
