# Generated by Django 5.2.7 on 2025-11-04 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Granja",
                "verbose_name_plural": "Granjas",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ChickenHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "area_m2",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Area (m2)"
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chicken_houses",
                        to="production.farm",
                        verbose_name="Granja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galpon",
                "verbose_name_plural": "Galpones",
                "ordering": ("farm__name", "name"),
                "unique_together": {("farm", "name")},
            },
        ),
        migrations.CreateModel(
            name="BirdBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activo"), ("inactive", "Inactivo")],
                        default="active",
                        max_length=8,
                        verbose_name="Estado",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Fecha de nacimiento")),
                (
                    "initial_quantity",
                    models.PositiveIntegerField(verbose_name="Cantidad inicial"),
                ),
                ("breed", models.CharField(max_length=150, verbose_name="Raza")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bird_batches",
                        to="production.farm",
                        verbose_name="Granja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de aves",
                "verbose_name_plural": "Lotes de aves",
                "ordering": ("-birth_date", "farm__name"),
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "area_m2",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Area (m2)"
                    ),
                ),
                (
                    "chicken_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="production.chickenhouse",
                        verbose_name="Galpon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salon",
                "verbose_name_plural": "Salones",
                "ordering": (
                    "chicken_house__farm__name",
                    "chicken_house__name",
                    "name",
                ),
                "unique_together": {("chicken_house", "name")},
            },
        ),
        migrations.CreateModel(
            name="BirdBatchRoomAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "bird_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="production.birdbatch",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="production.room",
                        verbose_name="Salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignacion de lote",
                "verbose_name_plural": "Asignaciones de lotes",
                "unique_together": {("bird_batch", "room")},
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('production', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Produccion')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo')),
                ('mortality', models.PositiveIntegerField(verbose_name='Mortalidad')),
                ('discard', models.PositiveIntegerField(verbose_name='Descarte')),
            ],
            options={
                'verbose_name': 'Registro de produccion',
                'verbose_name_plural': 'Registros de produccion',
                'ordering': ('-date',),
            },
        ),
    ]
