# Generated by Django 5.2.7 on 2025-11-04 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionrecord",
            name="bird_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_records",
                to="production.birdbatch",
                verbose_name="Lote de aves",
            ),
        ),
    ]
