# Generated by Django 5.0.14 on 2025-11-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("granjas", "0002_alter_birdbatch_options_and_more"),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionrecord",
            name="bird_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_records",
                to="granjas.birdbatch",
                verbose_name="Lote de aves",
            ),
        ),
    ]

