# Generated by Django 5.0.14 on 2025-11-02 20:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_rename_granjas_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='average_egg_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso promedio huevo (g)'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Registrado en'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records_updated', to=settings.AUTH_USER_MODEL, verbose_name='Última modificación por'),
        ),
        migrations.AddConstraint(
            model_name='productionrecord',
            constraint=models.UniqueConstraint(fields=('bird_batch', 'date'), name='uniq_production_record_per_batch_date'),
        ),
    ]
