# Generated by Django 5.0.14 on 2025-11-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionrecord_average_egg_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='average_egg_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso promedio huevo (g)'),
        ),
    ]
