# Generated by Codex on 2025-11-06 to link weight sessions with task assignments

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0020_alter_taskdefinition_record_format"),
        ("production", "0007_weightsamplesession_weightsample"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightsamplesession",
            name="task_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="weight_sessions",
                to="task_manager.taskassignment",
                verbose_name="Asignación de tarea",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weightsamplesession",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="weightsamplesession",
            constraint=models.UniqueConstraint(
                condition=Q(task_assignment__isnull=False),
                fields=("room", "task_assignment"),
                name="uniq_weight_session_assignment_room",
            ),
        ),
        migrations.AddConstraint(
            model_name="weightsamplesession",
            constraint=models.UniqueConstraint(
                condition=Q(task_assignment__isnull=True),
                fields=("date", "room"),
                name="uniq_weight_session_date_room_unassigned",
            ),
        ),
    ]
