# Generated by Django 5.0.14 on 2025-11-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_weightsamplesession_task_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chickenhouse',
            name='area_m2',
        ),
    ]
