# Generated by Django 5.0.14 on 2025-11-04 00:04

import django.db.models.deletion
from django.db import migrations, models


def link_room_records_forward(apps, schema_editor):
    WeightSampleSession = apps.get_model('production', 'WeightSampleSession')
    ProductionRoomRecord = apps.get_model('production', 'ProductionRoomRecord')

    session_qs = WeightSampleSession.objects.select_related('room').filter(
        production_record__isnull=False,
        room__isnull=False,
    )

    for session in session_qs.iterator():
        room_record = ProductionRoomRecord.objects.filter(
            production_record_id=session.production_record_id,
            room_id=session.room_id,
        ).first()
        if room_record:
            session.production_room_record_id = room_record.pk
            session.save(update_fields=['production_room_record'])


def link_room_records_backward(apps, schema_editor):
    WeightSampleSession = apps.get_model('production', 'WeightSampleSession')
    WeightSampleSession.objects.update(production_room_record=None)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_weightsample_id_alter_weightsamplesession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightsamplesession',
            name='production_room_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_sample_sessions', to='production.productionroomrecord', verbose_name='Registro de producción por salón'),
        ),
        migrations.RunPython(link_room_records_forward, link_room_records_backward),
    ]
