# Generated by Django 5.0.14 on 2025-11-15 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_breed_reference_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggClassificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_cartons', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cartones reportados')),
                ('received_cartons', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cartones recibidos')),
                ('notes', models.TextField(blank=True, verbose_name='Notas para conciliación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Recibido'), ('classified', 'Clasificado')], default='pending', max_length=16, verbose_name='Estado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado en')),
                ('classified_at', models.DateTimeField(blank=True, null=True, verbose_name='Clasificado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bird_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_classifications', to='production.birdbatch', verbose_name='Lote')),
                ('classified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_batches_classified', to=settings.AUTH_USER_MODEL, verbose_name='Clasificado por')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_batches_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('production_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='egg_classification', to='production.productionrecord', verbose_name='Registro de producción')),
            ],
            options={
                'verbose_name': 'Lote de clasificación de huevo',
                'verbose_name_plural': 'Lotes de clasificación de huevo',
                'ordering': ('-production_record__date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EggClassificationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egg_type', models.CharField(choices=[('jumbo', 'Jumbo'), ('aaa', 'AAA'), ('aa', 'AA'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=8, verbose_name='Tipo de huevo')),
                ('cartons', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cartones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_entries', to='production.eggclassificationbatch', verbose_name='Lote de clasificación')),
            ],
            options={
                'verbose_name': 'Resultado de clasificación',
                'verbose_name_plural': 'Resultados de clasificación',
                'ordering': ('batch', 'egg_type'),
                'unique_together': {('batch', 'egg_type')},
            },
        ),
    ]
