# Generated by Django 5.0.14 on 2025-11-15 01:22

from django.db import migrations


def create_classification_batches(apps, schema_editor):
    ProductionRecord = apps.get_model("production", "ProductionRecord")
    EggClassificationBatch = apps.get_model("production", "EggClassificationBatch")

    batch_models = []
    existing_ids = set(
        EggClassificationBatch.objects.values_list("production_record_id", flat=True)
    )
    for record in ProductionRecord.objects.select_related("bird_batch").iterator():
        if record.pk in existing_ids:
            continue
        batch_models.append(
            EggClassificationBatch(
                production_record_id=record.pk,
                bird_batch_id=record.bird_batch_id,
                reported_cartons=record.production,
            )
        )

    if batch_models:
        EggClassificationBatch.objects.bulk_create(batch_models, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_eggclassificationbatch_eggclassificationentry'),
    ]

    operations = [
        migrations.RunPython(
            code=create_classification_batches,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
