# Generated by Django 5.0.14 on 2025-11-16 01:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def assign_default_sessions(apps, schema_editor):
    Batch = apps.get_model('production', 'EggClassificationBatch')
    Session = apps.get_model('production', 'EggClassificationSession')
    Entry = apps.get_model('production', 'EggClassificationEntry')
    timezone = django.utils.timezone

    batch_ids = (
        Entry.objects.filter(session__isnull=True)
        .values_list('batch_id', flat=True)
        .distinct()
    )
    for batch_id in batch_ids:
        batch = Batch.objects.get(pk=batch_id)
        classified_at = batch.classified_at or timezone.now()
        session = Session.objects.create(
            batch=batch,
            classified_at=classified_at,
            classified_by=batch.classified_by,
            notes="Migración automática",
        )
        Entry.objects.filter(batch=batch, session__isnull=True).update(session=session)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_convert_reported_cartons_to_cartons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eggclassificationentry',
            options={'ordering': ('session', 'egg_type'), 'verbose_name': 'Resultado de clasificación', 'verbose_name_plural': 'Resultados de clasificación'},
        ),
        migrations.CreateModel(
            name='EggClassificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Clasificado en')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_sessions', to='production.eggclassificationbatch', verbose_name='Lote de clasificación')),
                ('classified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_classification_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Clasificado por')),
            ],
            options={
                'verbose_name': 'Sesión de clasificación de huevo',
                'verbose_name_plural': 'Sesiones de clasificación de huevo',
                'ordering': ('-classified_at', '-created_at'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='eggclassificationentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eggclassificationentry',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='production.eggclassificationsession', verbose_name='Sesión de clasificación'),
        ),
        migrations.AlterUniqueTogether(
            name='eggclassificationentry',
            unique_together={('session', 'egg_type')},
        ),
        migrations.RunPython(assign_default_sessions, reverse_code=noop),
        migrations.AlterField(
            model_name='eggclassificationentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='production.eggclassificationsession', verbose_name='Sesión de clasificación'),
        ),
    ]
