# Generated by Django 5.0.14 on 2025-11-16 02:16

from django.db import migrations
from django.db.models import Count


def delete_empty_classification_sessions(apps, schema_editor):
    Session = apps.get_model("production", "EggClassificationSession")
    empty_sessions = Session.objects.annotate(entry_count=Count("entries")).filter(entry_count=0)
    total = empty_sessions.count()
    if total:
        empty_sessions.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_alter_eggclassificationentry_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            delete_empty_classification_sessions,
            reverse_code=noop,
        ),
    ]
