# Generated by Django 5.0.14 on 2025-11-16 16:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_alter_eggclassificationbatch_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de despacho')),
                ('destination', models.CharField(choices=[('tierralta', 'Tierralta'), ('monteria', 'Montería'), ('bajo_cauca', 'Bajo Cauca')], max_length=32, verbose_name='Destino')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('total_cartons', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total cartones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_dispatches_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_dispatches_driven', to=settings.AUTH_USER_MODEL, verbose_name='Conductor')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_dispatches_sold', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor responsable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_dispatches_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Despacho de huevo',
                'verbose_name_plural': 'Despachos de huevo',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EggDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egg_type', models.CharField(choices=[('jumbo', 'Jumbo'), ('aaa', 'AAA'), ('aa', 'AA'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=8, verbose_name='Tipo de huevo')),
                ('cartons', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cartones despachados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.eggdispatch', verbose_name='Despacho')),
            ],
            options={
                'verbose_name': 'Detalle de despacho',
                'verbose_name_plural': 'Detalles de despacho',
                'ordering': ('egg_type',),
                'unique_together': {('dispatch', 'egg_type')},
            },
        ),
    ]
