# Generated by Django 5.0.14 on 2025-11-13 15:00

from django.db import migrations, models
import django.db.models.deletion


def assign_default_destination(apps, schema_editor):
    ChickenHouse = apps.get_model("production", "ChickenHouse")
    for house in ChickenHouse.objects.select_related("farm").all():
        if house.egg_destination_farm_id:
            continue
        house.egg_destination_farm_id = house.farm_id
        house.save(update_fields=["egg_destination_farm"])


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0020_eggdispatch_eggdispatchitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="chickenhouse",
            name="egg_destination_farm",
            field=models.ForeignKey(
                blank=True,
                help_text="Selecciona la granja a la que se debe enviar la producción de este galpón.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="egg_destination_chicken_houses",
                to="production.farm",
                verbose_name="Granja destino del huevo",
            ),
        ),
        migrations.RunPython(assign_default_destination, migrations.RunPython.noop),
    ]
