# Generated by Django 5.0.14 on 2025-11-19 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_chickenhouse_destination_farm'),
        ('personal', '0030_alter_role_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_authorized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Autorizado en'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_transport_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_destination_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_transport_batches', to='production.farm', verbose_name='Granja destino'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada de transporte'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_progress_step',
            field=models.CharField(blank=True, max_length=32, verbose_name='Paso de transporte'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_status',
            field=models.CharField(choices=[('pending', 'Pendiente de transporte'), ('authorized', 'Autorizado'), ('in_transit', 'En transporte'), ('verification', 'En verificación'), ('verified', 'Verificado')], default='pending', max_length=16, verbose_name='Estado de transporte'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_transport_assignments', to='personal.userprofile', verbose_name='Transportador'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verificado en'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_transport_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_verified_cartons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cartones verificados'),
        ),
    ]
