# Generated by Django 5.0.14 on 2025-11-20 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_eggclassificationbatch_transport_authorized_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado por transportador en'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_transport_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por transportador'),
        ),
        migrations.AddField(
            model_name='eggclassificationbatch',
            name='transport_confirmed_cartons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cartones confirmados por transportador'),
        ),
    ]
