# Generated by Django 5.0.14 on 2025-12-09 18:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0044_product_category'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('production', '0023_eggclassificationbatch_transport_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConsumptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_consumption_configs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_configs', to='administration.product')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_consumption_configs', to='production.room')),
            ],
            options={
                'verbose_name': 'Configuración de consumo por salón',
                'verbose_name_plural': 'Configuraciones de consumo por salón',
                'ordering': ('room__chicken_house__name', 'room__name', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('receipt', 'Ingreso'), ('consumption', 'Consumo automático'), ('manual_consumption', 'Consumo manual'), ('reset', 'Reseteo'), ('adjustment', 'Ajuste')], max_length=32)),
                ('scope', models.CharField(choices=[('company', 'General'), ('farm', 'Granja'), ('chicken_house', 'Galpón')], max_length=20)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('reference_type', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('chicken_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='production.chickenhouse')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries_executed', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='production.farm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='administration.product')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries_recorded', to=settings.AUTH_USER_MODEL)),
                ('reference_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ('-effective_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('company', 'General'), ('farm', 'Granja'), ('chicken_house', 'Galpón')], default='company', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('chicken_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='production.chickenhouse')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='production.farm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='administration.product')),
            ],
            options={
                'verbose_name': 'Saldo de inventario',
                'verbose_name_plural': 'Saldos de inventario',
                'unique_together': {('product', 'scope', 'farm', 'chicken_house')},
            },
        ),
    ]
