# Generated by Django 5.2.7 on 2025-10-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calendario', '0003_remove_positiondefinition_shift_type_and_more')]


    dependencies = [
        ('personal', '0002_positiondefinition_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positiondefinition',
            name='shift_type',
        ),
        migrations.AlterField(
            model_name='operatorcapability',
            name='max_complexity',
            field=models.CharField(choices=[('basic', 'Manejable'), ('intermediate', 'Importante'), ('advanced', 'Crítico')], default='basic', max_length=16, verbose_name='Criticidad máxima manejada'),
        ),
        migrations.AlterField(
            model_name='operatorcapability',
            name='min_complexity',
            field=models.CharField(choices=[('basic', 'Manejable'), ('intermediate', 'Importante'), ('advanced', 'Crítico')], default='basic', max_length=16, verbose_name='Criticidad mínima'),
        ),
        migrations.AlterField(
            model_name='positiondefinition',
            name='allow_lower_complexity',
            field=models.BooleanField(default=False, verbose_name='Permitir cubrir con criticidad inferior'),
        ),
        migrations.AlterField(
            model_name='positiondefinition',
            name='complexity',
            field=models.CharField(choices=[('basic', 'Manejable'), ('intermediate', 'Importante'), ('advanced', 'Crítico')], default='basic', max_length=16, verbose_name='Nivel de criticidad'),
        ),
        migrations.AlterField(
            model_name='restrule',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Día'), ('night', 'Noche'), ('mixed', 'Mixto')], default='day', max_length=16, verbose_name='Turno'),
        ),
    ]
