# Generated by Django 5.0.14 on 2025-10-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('calendario', '0010_rename_calendario_o_operato_0eec88_idx_calendario__operato_4c829a_idx_and_more')]


    dependencies = [
        ('personal', '0009_operatorrestperiod'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='operatorrestperiod',
            new_name='calendario__operato_4c829a_idx',
            old_name='calendario_o_operato_0eec88_idx',
        ),
        migrations.RenameIndex(
            model_name='operatorrestperiod',
            new_name='calendario__operato_8d9126_idx',
            old_name='calendario_o_operato_a71ea4_idx',
        ),
    ]
