# Generated by Django 5.0.14 on 2025-10-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('calendario', '0013_remove_positiondefinition_allow_lower_complexity_and_more')]


    dependencies = [
        ('personal', '0012_positioncategory_automatic_rest_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positiondefinition',
            name='allow_lower_complexity',
        ),
        migrations.RemoveField(
            model_name='positiondefinition',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='positiondefinition',
            name='notes',
        ),
    ]
