# Generated by Django 5.0.14 on 2025-10-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('calendario', '0016_remove_positioncategory_automatic_rest_days')]


    dependencies = [
        ('personal', '0015_alter_positioncategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positioncategory',
            name='automatic_rest_days',
        ),
    ]
