# Generated by Django 5.0.14 on 2025-10-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('calendario', '0017_remove_positiondefinition_is_active')]


    dependencies = [
        ('personal', '0016_remove_positioncategory_automatic_rest_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positiondefinition',
            name='is_active',
        ),
    ]
