# Generated by Django 5.0.14 on 2025-11-02 03:17

import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models

CODE_DISPLAY_MAP = {
    "view_users": "Ver usuarios",
    "manage_users": "Gestionar usuarios",
    "view_roles": "Ver roles",
    "manage_roles": "Gestionar roles",
}


def copy_role_permissions_forward(apps, schema_editor):
    RolePermission = apps.get_model("personal", "RolePermission")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type, _ = ContentType.objects.get_or_create(app_label="personal", model="role")

    for role_permission in RolePermission.objects.all():
        permission_code = getattr(role_permission, "permission_code", "")
        if not permission_code:
            continue

        permission_defaults = {"name": CODE_DISPLAY_MAP.get(permission_code, permission_code.replace("_", " ").title())}
        permission, _ = Permission.objects.get_or_create(
            content_type=content_type,
            codename=permission_code,
            defaults=permission_defaults,
        )
        role_permission.permission = permission
        role_permission.save(update_fields=["permission"])


def copy_role_permissions_backward(apps, schema_editor):
    RolePermission = apps.get_model("personal", "RolePermission")

    for role_permission in RolePermission.objects.select_related("permission"):
        permission = getattr(role_permission, "permission", None)
        if permission is None:
            continue
        role_permission.permission_code = permission.codename
        role_permission.save(update_fields=["permission_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('personal', '0020_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='personal.RolePermission', to='auth.permission', verbose_name='Permisos'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='auth.permission'),
        ),
        migrations.RunPython(copy_role_permissions_forward, copy_role_permissions_backward),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission_code',
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='auth.permission'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role__name', 'permission__content_type__app_label', 'permission__codename'], 'verbose_name': 'Permiso por rol', 'verbose_name_plural': 'Permisos por rol'},
        ),
    ]
