# Generated by Django 5.0.14 on 2025-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0024_add_vacunador_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioncategory',
            name='code',
            field=models.CharField(choices=[('GALPONERO_PRODUCCION_DIA', 'Galponero producción día'), ('GALPONERO_LEVANTE_DIA', 'Galponero levante día'), ('GALPONERO_PRODUCCION_NOCHE', 'Galponero producción noche'), ('GALPONERO_LEVANTE_NOCHE', 'Galponero levante noche'), ('CLASIFICADOR_DIA', 'Clasificador día'), ('CLASIFICADOR_NOCHE', 'Clasificador noche'), ('LIDER_GRANJA', 'Líder de granja'), ('SUPERVISOR', 'Supervisor'), ('LIDER_TECNICO', 'Líder técnico'), ('OFICIOS_VARIOS', 'Oficios varios'), ('VACUNADOR', 'Vacunador'), ('AUXILIAR_OPERATIVO', 'Auxiliar operativo')], max_length=64, unique=True, verbose_name='Código'),
        ),
    ]
