# Generated by Django 5.0.14 on 2025-11-12 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0025_alter_positioncategory_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('payment_type', models.CharField(choices=[('daily', 'Pago por día laboral'), ('monthly', 'Pago mensual (2 quincenas)')], max_length=16, verbose_name='Esquema de pago')),
                ('effective_from', models.DateField(verbose_name='Vigente desde')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salario de colaborador',
                'verbose_name_plural': 'Salarios de colaboradores',
                'db_table': 'users_operator_salary',
                'ordering': ['operator_id', 'effective_from', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='operatorsalary',
            constraint=models.CheckConstraint(check=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='operator_salary_valid_range'),
        ),
    ]
