# Generated by Django 5.0.14 on 2025-11-13 23:25

import django.db.models.deletion
from django.db import migrations, models


NEW_CATEGORIES = {
    "ADMINISTRADOR": {"shift_type": "day"},
    "AUXILIAR_ADMINISTRATIVO": {"shift_type": "day"},
    "AUXILIAR_CONTABLE": {"shift_type": "day"},
    "CONTADOR": {"shift_type": "day"},
    "ASESOR": {"shift_type": "day"},
    "ADMINISTRATIVO_OTRO": {"shift_type": "day"},
    "VENDEDOR": {"shift_type": "day"},
    "TRANSPORTADOR": {"shift_type": "day"},
    "AUXILIAR_VENTAS": {"shift_type": "day"},
}


def seed_new_position_categories(apps, schema_editor):
    PositionCategory = apps.get_model("personal", "PositionCategory")
    for code, config in NEW_CATEGORIES.items():
        PositionCategory.objects.update_or_create(
            code=code,
            defaults={
                "shift_type": config.get("shift_type", "day"),
                "rest_max_consecutive_days": 8,
                "rest_post_shift_days": 0,
                "rest_monthly_days": 5,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0028_operatorsalary_rest_days_per_week'),
        ('production', '0013_breed_reference_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioncategory',
            name='code',
            field=models.CharField(choices=[('GALPONERO_PRODUCCION_DIA', 'Galponero producción día'), ('GALPONERO_LEVANTE_DIA', 'Galponero levante día'), ('GALPONERO_PRODUCCION_NOCHE', 'Galponero producción noche'), ('GALPONERO_LEVANTE_NOCHE', 'Galponero levante noche'), ('CLASIFICADOR_DIA', 'Clasificador día'), ('CLASIFICADOR_NOCHE', 'Clasificador noche'), ('LIDER_GRANJA', 'Líder de granja'), ('SUPERVISOR', 'Supervisor'), ('LIDER_TECNICO', 'Líder técnico'), ('OFICIOS_VARIOS', 'Oficios varios'), ('VACUNADOR', 'Vacunador'), ('AUXILIAR_OPERATIVO', 'Auxiliar operativo'), ('ADMINISTRADOR', 'Administrador'), ('AUXILIAR_ADMINISTRATIVO', 'Auxiliar administrativo'), ('AUXILIAR_CONTABLE', 'Auxiliar contable'), ('CONTADOR', 'Contador'), ('ASESOR', 'Asesor'), ('ADMINISTRATIVO_OTRO', 'Otro'), ('VENDEDOR', 'Vendedor'), ('TRANSPORTADOR', 'Transportador'), ('AUXILIAR_VENTAS', 'Auxiliar ventas')], max_length=64, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='positiondefinition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='personal.positioncategory', verbose_name='Sub-categoría'),
        ),
        migrations.AlterField(
            model_name='positiondefinition',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position_definitions', to='production.farm', verbose_name='Granja'),
        ),
        migrations.AlterField(
            model_name='positiondefinition',
            name='job_type',
            field=models.CharField(choices=[('production', 'Producción'), ('classification', 'Clasificación'), ('administrative', 'Administración'), ('sales', 'Ventas')], default='production', max_length=32, verbose_name='Tipo de puesto'),
        ),
        migrations.RunPython(seed_new_position_categories, migrations.RunPython.noop),
    ]
