# Generated by Django 5.0.14 on 2025-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0029_alter_positioncategory_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('GALPONERO', 'Galponero'), ('CLASIFICADOR', 'Clasificador'), ('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('TRANSPORTADOR', 'Transportador'), ('VENDEDOR', 'Vendedor')], max_length=32, unique=True),
        ),
    ]
