# Generated by Django 5.0.14 on 2025-11-24 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0030_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRestSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Descanso programado')),
                ('suggested_date', models.DateField(verbose_name='Descanso sugerido')),
                ('reason', models.TextField(max_length=600, verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('acknowledged', 'Atendida'), ('dismissed', 'Descartada')], default='pending', max_length=16, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_suggestions', to='personal.shiftcalendar', verbose_name='Calendario')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('rest_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='personal.operatorrestperiod', verbose_name='Descanso asociado')),
            ],
            options={
                'verbose_name': 'Sugerencia de descanso',
                'verbose_name_plural': 'Sugerencias de descanso',
                'db_table': 'calendario_rest_suggestion',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='calendarrestsuggestion',
            constraint=models.UniqueConstraint(fields=('calendar', 'operator', 'scheduled_date'), name='unique_rest_suggestion_per_day'),
        ),
    ]
