# Generated by Django 5.0.14 on 2025-10-31 18:25

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationdispatch',
            new_name='notificatio_status_3801bc_idx',
            old_name='notification_status_cf6188_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdispatch',
            new_name='notificatio_channel_6209dd_idx',
            old_name='notification_channel_2b838c_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='notificatio_topic_i_ea6948_idx',
            old_name='notification_topic__6d808b_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramchatlink',
            new_name='notificatio_status_cbe1f4_idx',
            old_name='notification_status_83b4c7_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramchatlink',
            new_name='notificatio_bot_id_3b2b50_idx',
            old_name='notification_bot_id_ae5099_idx',
        ),
        migrations.AlterField(
            model_name='notificationdispatch',
            name='payload',
            field=models.JSONField(blank=True, default=notifications.models._default_json_dict, help_text='Datos ya renderizados listos para enviar al canal.', verbose_name='Payload de mensaje'),
        ),
        migrations.AlterField(
            model_name='notificationdispatch',
            name='response_meta',
            field=models.JSONField(blank=True, default=notifications.models._default_json_dict, verbose_name='Respuesta canal'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='context',
            field=models.JSONField(blank=True, default=notifications.models._default_json_dict, help_text='Payload normalizado con información necesaria para renderizar la plantilla.', verbose_name='Contexto'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='extra_options',
            field=models.JSONField(blank=True, default=notifications.models._default_json_dict, help_text='Parámetros adicionales para el envío al canal seleccionado.', verbose_name='Opciones adicionales'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='keyboard',
            field=models.JSONField(blank=True, default=notifications.models._default_json_dict, help_text='Opcional: estructura de botones inline o teclado personalizado.', verbose_name='Keyboard'),
        ),
        migrations.AlterField(
            model_name='telegramchatlink',
            name='metadata',
            field=models.JSONField(blank=True, default=notifications.models._default_json_dict, verbose_name='Metadatos adicionales'),
        ),
    ]
